@startuml
skinparam componentStyle uml2

component [LanguageCore]
note top of [LanguageCore]
Provides the Context Mapper DSL 
(CML) modeling language to express 
architectures on the basis of 
Strategic Domain-driven Design 
(DDD) patterns. 
end note

component [ArchitecturalRefactorings]
note bottom of [ArchitecturalRefactorings]
Architectural Refactorings (ARs) 
allow to improve the architecture 
model iteratively. 
end note

component [StructuredServiceDecomposition]
note bottom of [StructuredServiceDecomposition]
The Service Cutter integration 
into Context Mapper allows to 
analyze the Context Map with respect 
to coupling criteria and supports 
to suggest improved Context Maps. 

end note

component [DiscoveryLibrary]
note left of [DiscoveryLibrary]
The reverse engineering and discovery 
component can generate CML Context Maps 
from existing source code. This allows 
to reverse engineer the architecture 
model in projects with existing monoliths 
or microservices. 

end note

component [Generators]
note right of [Generators]
The generators allow to generate 
other representations of the architecture 
derived by a given CML Context 
Map. 
end note

interface "Upstream-Downstream" as DiscoveryLibrary_to_LanguageCore
[LanguageCore] -up-> DiscoveryLibrary_to_LanguageCore : PUBLISHED_LANGUAGE
[DiscoveryLibrary] ..> DiscoveryLibrary_to_LanguageCore : " use as CONFORMIST"

interface "Upstream-Downstream" as StructuredServiceDecomposition_to_LanguageCore
[LanguageCore] -left-> StructuredServiceDecomposition_to_LanguageCore : PUBLISHED_LANGUAGE
[StructuredServiceDecomposition] .> StructuredServiceDecomposition_to_LanguageCore : "      use" 

[LanguageCore] <-> [ArchitecturalRefactorings] : "    Shared Kernel    "

interface "Upstream-Downstream" as Generators_to_LanguageCore
[LanguageCore] -down-> Generators_to_LanguageCore : " PUBLISHED_LANGUAGE"
Generators_to_LanguageCore <.. [Generators] : " use"
@enduml