@startuml
skinparam componentStyle uml2

component [LanguageCore]
note top of [LanguageCore]
Provides the Context Mapper DSL 
(CML) modeling language to express 
architectures on the basis of 
Strategic Domain-driven Design 
(DDD) patterns. 
end note

component [ArchitecturalRefactorings]
note bottom of [ArchitecturalRefactorings]
Architectural Refactorings (ARs) 
allow to improve the architecture 
model iteratively. 
end note

component [StructuredServiceDecomposition]
note bottom of [StructuredServiceDecomposition]
The Service Cutter integration into Context 
Mapper allows to analyze the Context Map 
with respect to coupling criteria and 
supports to suggest improved Context Maps.
The Service Cutter library exposes an API
(Open Host Service and Published Language)
used by Context Mapper to generate the
new decompositions. 
end note

component [DiscoveryLibrary]
note left of [DiscoveryLibrary]
The reverse engineering and discovery 
component can generate CML Context Maps 
from existing source code. This allows 
to reverse engineer the architecture 
model in projects with existing monoliths 
or microservices. 
end note

component [Generators]
note right of [Generators]
The generators allow to generate 
other representations of the architecture 
derived by a given CML Context 
Map. 
end note

interface "Upstream-Downstream" as DiscoveryLibrary_to_LanguageCore
[LanguageCore] -up-> DiscoveryLibrary_to_LanguageCore : "PUBLISHED_LANGUAGE (PL)"
[DiscoveryLibrary] ..> DiscoveryLibrary_to_LanguageCore : " use as CONFORMIST (CF)"

interface "Upstream-Downstream" as LanguageCore_to_StructuredServiceDecomposition
[StructuredServiceDecomposition] -right-> LanguageCore_to_StructuredServiceDecomposition : "OHS, PL"
LanguageCore_to_StructuredServiceDecomposition <. [LanguageCore] : "use via ACL" 

[LanguageCore] <-> [ArchitecturalRefactorings] : "    Shared Kernel    "

interface "Upstream-Downstream" as Generators_to_LanguageCore
[LanguageCore] -down-> Generators_to_LanguageCore : " PUBLISHED_LANGUAGE (PL)"
Generators_to_LanguageCore <.. [Generators] : " use"
@enduml