tasks:
  - init: ./gradlew build
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - jebbs.plantuml@2.13.12:LcphKtCbPTIScvq6ELiS8Q==
    - contextmapper.context-mapper-vscode-extension@6.3.0:BkS+dr2rMIvQQrBzNJhoxg==