tasks:
  - init: ./gradlew build
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - jebbs.plantuml@2.13.12:LcphKtCbPTIScvq6ELiS8Q==
    - contextmapper.context-mapper-vscode-extension@5.14.0:lMMh+QPbMb01p3zu5ziprg==