tasks:
  - init: ./gradlew build
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - jebbs.plantuml@2.13.12:LcphKtCbPTIScvq6ELiS8Q==
    - contextmapper.context-mapper-vscode-extension@6.1.0:8GFbvb1Hm4qGvvP4s6Yi5A==